language: node
platform: linux
nodeVersion: 18-lts
preBuild:
  - npm ci
build:
  - npm run build
postBuild:
  - npm prune --production
startupCommand: node server.js
appSettings:
  - name: PORT
    value: 8080
  - name: NODE_ENV
    value: production
  - name: WEBSITES_PORT
    value: 8080 